### ISSUE TITLE
总体整合

### ISSUE THREAD

**Issue by leviding** [xitu/Under-the-hood-ReactJS#18]
将本系列文章整合为一篇长文，文中图片自己上传 CDN 或者用本 Repo 的链接（需要你在链接中补充 `https://github.com/xitu/Under-the-hood-ReactJS/tree/translation/stack/images` 这个前缀，否则本文离开本项目无法正常显示），整理好后进行 PR，PR 被 Merge 后，你需要将本长文发布到掘金上。

https://github.com/xitu/Under-the-hood-ReactJS/blob/translation/stack/book/Under-the-hood-ReactJS

**Comment by blizzardzheng** [comment]
认领

**Comment by leviding** [comment]
好的 @blizzardzheng
