### ISSUE TITLE
Under-the-hood-ReactJS/Intro.md

### ISSUE THREAD

**Issue by leviding** [xitu/Under-the-hood-ReactJS#2]
- Markdown: [Under-the-hood-ReactJS/Intro.md](https://github.com/xitu/Under-the-hood-ReactJS/blob/translation/stack/book/Intro.md)
- 翻译积分：1
- PR: #21

**Comment by undead25** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
好的
